import { toast } from "vue-sonner";

export const showErrorToast = function (string) {
    return toast.error(string);
};

export const showSuccessToast = function (string) {
    return toast.success(string);
};

export const formatDate = function (date) {
    return new Date(date).toLocaleDateString("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric",
    });
};

export const roomTypes = [
    { value: "Apartment", text: "Apartment" },
    { value: "Single", text: "Single" },
    { value: "Studio", text: "Studio" },
    { value: "Family", text: "Family" },
    { value: "Twin_Double", text: "Twin/Double" },
    { value: "Dormitory_room", text: "Dormitory room" },
    { value: "Bed_in_Dormitory", text: "Bed in Dormitory" },
    { value: "Bungalow", text: "Bungalow" },
    { value: "Chalet", text: "Chalet" },
    { value: "Holiday_home", text: "Holiday home" },
    { value: "Villa", text: "Villa" },
    { value: "Mobile_home", text: "Mobile home" },
    { value: "Tent", text: "Tent" },
    { value: "Quadruple", text: "Quadruple" },
    { value: "Suite", text: "Suite" },
    { value: "Triple", text: "Triple" },
    { value: "Twin", text: "Twin" },
    { value: "Double", text: "Double" },
];

export const getPropertyTypes = [
    { value: "HOUSE", label: "House" },
    { value: "COTTAGE", label: "Cottage" },
    { value: "CONDO", label: "Condominium" },
    { value: "BEDANDBREAKFAST", label: "Bnb" },
    { value: "VILLA", label: "Villa" },
    { value: "CHALET", label: "Chalet" },
    { value: "CABIN", label: "Cabin" },
    { value: "STUDIO", label: "Studio" },
    { value: "ROOM", label: "Room" },
    { value: "APARTMENT", label: "Apartment" },
    { value: "HOTEL", label: "Hotel" },
    { value: "HOSTEL", label: "Hostel" },
    { value: "LODGE", label: "Lodge" },
    { value: "TOWNHOUSE", label: "Townhouse" },
    { value: "DUPLEX", label: "Duplex" },
    { value: "TRIPLEX", label: "Triplex" },
    { value: "FOURPLEX", label: "Fourplex" },
    { value: "BUNGALOW", label: "Bungalow" },
    { value: "FARMHOUSE", label: "Farmhouse" },
    { value: "BOAT", label: "Boat" },
    { value: "HOUSEBOAT", label: "Houseboat" },
    { value: "RESORT", label: "Resort" },
    { value: "PENTHOUSE", label: "Penthouse" },
    { value: "CHATEAU", label: "Castle" },
    { value: "GUESTHOUSE", label: "Guest House" },
    { value: "HOMESTAY", label: "Homestay" },
    { value: "CAMPGROUND", label: "Campground" },
    { value: "MOTELROOM", label: "Motel Room" },
    { value: "COUNTRYHOUSE", label: "Country House" },
    { value: "LOFT", label: "Loft" },
    { value: "DORM", label: "Dorm" },
    { value: "TREEHOUSE", label: "Treehouse" },
    { value: "PLANE", label: "Plane" },
    { value: "IGLOO", label: "Igloo" },
    { value: "RV", label: "RV" },
    { value: "LIGHTHOUSE", label: "Lighthouse" },
    { value: "YURT", label: "Yurt" },
    { value: "TIPI", label: "Tipi" },
    { value: "CAVE", label: "Cave" },
    { value: "ISLAND", label: "Island" },
    { value: "EARTHHOUSE", label: "Earthhouse" },
    { value: "HUT", label: "Hut" },
    { value: "TRAIN", label: "Train" },
    { value: "TENT", label: "Tent" },
    { value: "SERVICED_APARTMENT", label: "Serviced Apartment" },
    { value: "TINY_HOUSE", label: "Tiny House" },
    { value: "BOUTIQUE_HOTEL", label: "Boutique Hotel" },
    { value: "APARTHOTEL", label: "ApartHotel" },
    { value: "DOME_HOUSE", label: "Dome House" },
    { value: "CYCLADIC_HOUSE", label: "Cycladic House" },
    { value: "DAMMUSO", label: "Dammuso" },
    { value: "GUEST_SUITE", label: "Guest Suite" },
    { value: "HERITAGE_HOTEL", label: "Heritage Hotel" },
    { value: "HOLIDAY_PARK", label: "Holiday Park" },
    { value: "KEZHAN", label: "Kezhan" },
    { value: "MINSU", label: "Minsu" },
    { value: "PENSION", label: "Pension" },
    { value: "RANCH", label: "Ranch" },
    { value: "RELIGIOUS_BUILDING", label: "Religious Building" },
    { value: "RIAD", label: "Riad" },
    { value: "RYOKAN", label: "Ryokan" },
    { value: "SHEPHERDS_HUT", label: "Shepherds Hut" },
    { value: "SHIPPING_CONTAINER", label: "Shipping Container" },
    { value: "TOWER", label: "Tower" },
    { value: "TRULLO", label: "Trullo" },
    { value: "BARN", label: "Barn" },
    { value: "WINDMILL", label: "Windmill" },
    { value: "CASA_PARTICULAR", label: "Casa particular" },
    { value: "SAMPLE", label: "Sample Property" },
    { value: "OTHER", label: "Other" },
];

export const getCountries = [
    { code: "AF", name: "Afghanistan" },
    { code: "AL", name: "Albania" },
    { code: "DZ", name: "Algeria" },
    { code: "AS", name: "American Samoa" },
    { code: "AD", name: "Andorra" },
    { code: "AO", name: "Angola" },
    { code: "AI", name: "Anguilla" },
    { code: "AG", name: "Antigua and Barbuda" },
    { code: "AR", name: "Argentina" },
    { code: "AM", name: "Armenia" },
    { code: "AW", name: "Aruba" },
    { code: "AU", name: "Australia" },
    { code: "AT", name: "Austria" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "BS", name: "Bahamas" },
    { code: "BH", name: "Bahrain" },
    { code: "BD", name: "Bangladesh" },
    { code: "BB", name: "Barbados" },
    { code: "BY", name: "Belarus" },
    { code: "BE", name: "Belgium" },
    { code: "BZ", name: "Belize" },
    { code: "BJ", name: "Benin" },
    { code: "BM", name: "Bermuda" },
    { code: "BT", name: "Bhutan" },
    { code: "BO", name: "Bolivia" },
    { code: "BA", name: "Bosnia" },
    { code: "BW", name: "Botswana" },
    { code: "BR", name: "Brazil" },
    { code: "BN", name: "Brunei Darussalam" },
    { code: "BG", name: "Bulgaria" },
    { code: "BF", name: "Burkina Faso" },
    { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
    { code: "BI", name: "Burundi" },
    { code: "KH", name: "Cambodia" },
    { code: "CM", name: "Cameroon" },
    { code: "CA", name: "Canada" },
    { code: "CV", name: "Cape Verde" },
    { code: "KY", name: "Cayman Islands" },
    { code: "CF", name: "Central African Republic" },
    { code: "TD", name: "Chad" },
    { code: "CL", name: "Chile" },
    { code: "CN", name: "China" },
    { code: "CO", name: "Colombia" },
    { code: "KM", name: "Comoros" },
    { code: "CG", name: "Congo" },
    { code: "CR", name: "Costa Rica" },
    { code: "CI", name: "Ivory Coast" },
    { code: "HR", name: "Croatia" },
    { code: "CU", name: "Cuba" },
    { code: "CW", name: "Curaçao" },
    { code: "CY", name: "Cyprus" },
    { code: "CZ", name: "Czech Republic" },
    { code: "DK", name: "Denmark" },
    { code: "DJ", name: "Djibouti" },
    { code: "DM", name: "Dominica" },
    { code: "DO", name: "Dominican Republic" },
    { code: "EC", name: "Ecuador" },
    { code: "EG", name: "Egypt" },
    { code: "SV", name: "El Salvador" },
    { code: "GQ", name: "Equatorial Guinea" },
    { code: "ER", name: "Eritrea" },
    { code: "EE", name: "Estonia" },
    { code: "ET", name: "Ethiopia" },
    { code: "FJ", name: "Fiji" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "PF", name: "French Polynesia" },
    { code: "GA", name: "Gabon" },
    { code: "GM", name: "Gambia" },
    { code: "GE", name: "Georgia" },
    { code: "DE", name: "Germany" },
    { code: "GH", name: "Ghana" },
    { code: "GI", name: "Gibraltar" },
    { code: "GR", name: "Greece" },
    { code: "GL", name: "Greenland" },
    { code: "GD", name: "Grenada" },
    { code: "GU", name: "Guam" },
    { code: "GT", name: "Guatemala" },
    { code: "GN", name: "Guinea" },
    { code: "GW", name: "Guinea-Bissau" },
    { code: "GY", name: "Guyana" },
    { code: "HT", name: "Haiti" },
    { code: "VA", name: "Vatican City" },
    { code: "HN", name: "Honduras" },
    { code: "HK", name: "Hong Kong" },
    { code: "HU", name: "Hungary" },
    { code: "IS", name: "Iceland" },
    { code: "IN", name: "India" },
    { code: "ID", name: "Indonesia" },
    { code: "IR", name: "Iran" },
    { code: "IQ", name: "Iraq" },
    { code: "IE", name: "Ireland" },
    { code: "IL", name: "Israel" },
    { code: "IT", name: "Italy" },
    { code: "JM", name: "Jamaica" },
    { code: "JP", name: "Japan" },
    { code: "JO", name: "Jordan" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KE", name: "Kenya" },
    { code: "KI", name: "Kiribati" },
    { code: "KP", name: "North Korea" },
    { code: "KR", name: "South Korea" },
    { code: "KW", name: "Kuwait" },
    { code: "KG", name: "Kyrgyzstan" },
    { code: "LA", name: "Laos" },
    { code: "LV", name: "Latvia" },
    { code: "LB", name: "Lebanon" },
    { code: "LS", name: "Lesotho" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libya" },
    { code: "LI", name: "Liechtenstein" },
    { code: "LT", name: "Lithuania" },
    { code: "LU", name: "Luxembourg" },
    { code: "MO", name: "Macau" },
    { code: "MK", name: "Macedonia" },
    { code: "MG", name: "Madagascar" },
    { code: "MW", name: "Malawi" },
    { code: "MY", name: "Malaysia" },
    { code: "MV", name: "Maldives" },
    { code: "ML", name: "Mali" },
    { code: "MT", name: "Malta" },
    { code: "MH", name: "Marshall Islands" },
    { code: "MR", name: "Mauritania" },
    { code: "MU", name: "Mauritius" },
    { code: "YT", name: "Mayotte" },
    { code: "MX", name: "Mexico" },
    { code: "FM", name: "Micronesia" },
    { code: "MD", name: "Moldova" },
    { code: "MC", name: "Monaco" },
    { code: "MN", name: "Mongolia" },
    { code: "ME", name: "Montenegro" },
    { code: "MS", name: "Montserrat" },
    { code: "MA", name: "Morocco" },
    { code: "MZ", name: "Mozambique" },
    { code: "MM", name: "Myanmar" },
    { code: "NA", name: "Namibia" },
    { code: "NR", name: "Nauru" },
    { code: "NP", name: "Nepal" },
    { code: "NL", name: "Netherlands" },
    { code: "NC", name: "New Caledonia" },
    { code: "NZ", name: "New Zealand" },
    { code: "NI", name: "Nicaragua" },
    { code: "NE", name: "Niger" },
    { code: "NG", name: "Nigeria" },
    { code: "NU", name: "Niue" },
    { code: "NF", name: "Norfolk Island" },
    { code: "MP", name: "Northern Mariana Islands" },
    { code: "NO", name: "Norway" },
    { code: "OM", name: "Oman" },
    { code: "PK", name: "Pakistan" },
    { code: "PW", name: "Palau" },
    { code: "PA", name: "Panama" },
    { code: "PG", name: "Papua New Guinea" },
    { code: "PY", name: "Paraguay" },
    { code: "PE", name: "Peru" },
    { code: "PH", name: "Philippines" },
    { code: "PN", name: "Pitcairn" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "PR", name: "Puerto Rico" },
    { code: "QA", name: "Qatar" },
    { code: "RE", name: "Réunion" },
    { code: "RO", name: "Romania" },
    { code: "RU", name: "Russia" },
    { code: "RW", name: "Rwanda" },
    { code: "BL", name: "Saint Barthélemy" },
    { code: "SH", name: "Saint Helena" },
    { code: "KN", name: "Saint Kitts and Nevis" },
    { code: "LC", name: "Saint Lucia" },
    { code: "MF", name: "Saint Martin" },
    { code: "PM", name: "Saint Pierre and Miquelon" },
    { code: "VC", name: "Saint Vincent and the Grenadines" },
    { code: "WS", name: "Samoa" },
    { code: "SM", name: "San Marino" },
    { code: "ST", name: "São Tomé and Príncipe" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "SN", name: "Senegal" },
    { code: "RS", name: "Serbia" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SG", name: "Singapore" },
    { code: "SX", name: "Sint Maarten" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "SB", name: "Solomon Islands" },
    { code: "SO", name: "Somalia" },
    { code: "ZA", name: "South Africa" },
    {
        code: "GS",
        name: "South Georgia and the South Sandwich Islands",
    },
    { code: "SS", name: "South Sudan" },
    { code: "ES", name: "Spain" },
    { code: "LK", name: "Sri Lanka" },
    { code: "SD", name: "Sudan" },
    { code: "SR", name: "Suriname" },
    { code: "SZ", name: "Swaziland" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "SY", name: "Syria" },
    { code: "TW", name: "Taiwan" },
    { code: "TJ", name: "Tajikistan" },
    { code: "TZ", name: "Tanzania" },
    { code: "TH", name: "Thailand" },
    { code: "TL", name: "Timor-Leste" },
    { code: "TG", name: "Togo" },
    { code: "TK", name: "Tokelau" },
    { code: "TO", name: "Tonga" },
    { code: "TT", name: "Trinidad and Tobago" },
    { code: "TN", name: "Tunisia" },
    { code: "TR", name: "Turkey" },
    { code: "TM", name: "Turkmenistan" },
    { code: "TV", name: "Tuvalu" },
    { code: "UG", name: "Uganda" },
    { code: "UA", name: "Ukraine" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "GB", name: "United Kingdom" },
    { code: "US", name: "United States" },
    { code: "UM", name: "United States Minor Outlying Islands" },
    { code: "UY", name: "Uruguay" },
    { code: "UZ", name: "Uzbekistan" },
    { code: "VU", name: "Vanuatu" },
    { code: "VE", name: "Venezuela" },
    { code: "VN", name: "Vietnam" },
    { code: "VG", name: "British Virgin Islands" },
    { code: "VI", name: "United States Virgin Islands" },
    { code: "WF", name: "Wallis and Futuna" },
    { code: "EH", name: "Western Sahara" },
    { code: "YE", name: "Yemen" },
    { code: "ZM", name: "Zambia" },
    { code: "ZW", name: "Zimbabwe" },
];

export const getAllAmenities = [
    {
        amenity: "HAS_TV",
        category: "INDOOR",
        channels: {},
        label: "TV",
    },
    {
        amenity: "HAS_CABLE_TV",
        category: "INDOOR",
        channels: {},
        label: "Cable TV",
    },
    {
        amenity: "HAS_SMART_TV",
        category: "INDOOR",
        channels: {},
        label: "Smart TV",
    },
    {
        amenity: "HAS_AIR_CONDITIONING",
        category: "INDOOR",
        channels: {},
        label: "Air Conditioning",
    },
    {
        amenity: "HAS_HEATING",
        category: "INDOOR",
        channels: {},
        label: "Heating",
    },
    {
        amenity: "HAS_KITCHEN",
        category: "INDOOR",
        channels: {},
        label: "Kitchen",
    },
    {
        amenity: "HAS_KITCHENETTE",
        category: "INDOOR",
        channels: {},
        label: "Kitchenette",
    },
    {
        amenity: "HAS_INTERNET_WIFI",
        category: "INDOOR",
        channels: {},
        label: "Internet Wi-Fi",
    },
    {
        amenity: "HAS_PAID_WIFI",
        category: "INDOOR",
        channels: {},
        label: "Paid Wi-Fi",
    },
    {
        amenity: "HAS_WIFI_SPEED_25",
        category: "INDOOR",
        channels: {},
        label: "Wi-Fi Speed 25 Mbps",
    },
    {
        amenity: "HAS_WIFI_SPEED_50",
        category: "INDOOR",
        channels: {},
        label: "Wi-Fi Speed 50 Mbps",
    },
    {
        amenity: "HAS_WIFI_SPEED_100",
        category: "INDOOR",
        channels: {},
        label: "Wi-Fi Speed 100 Mbps",
    },
    {
        amenity: "HAS_WIFI_SPEED_250",
        category: "INDOOR",
        channels: {},
        label: "Wi-Fi Speed 250 Mbps",
    },
    {
        amenity: "HAS_WIFI_SPEED_500",
        category: "INDOOR",
        channels: {},
        label: "Wi-Fi Speed 500 Mbps",
    },
    {
        amenity: "HAS_WASHER",
        category: "INDOOR",
        channels: {},
        label: "Washer",
    },
    {
        amenity: "HAS_DRYER",
        category: "INDOOR",
        channels: {},
        label: "Dryer",
    },
    {
        amenity: "HAS_SHARED_WASHER",
        category: "INDOOR",
        channels: {},
        label: "Shared Washer",
    },
    {
        amenity: "HAS_SHARED_DRYER",
        category: "INDOOR",
        channels: {},
        label: "Shared Dryer",
    },
    {
        amenity: "HAS_POOL",
        category: "OUTDOOR",
        channels: {},
        label: "Pool",
    },
    {
        amenity: "HAS_POOL_ALL_YEAR",
        category: "OUTDOOR",
        channels: {},
        label: "Year-round Pool",
    },
    {
        amenity: "HAS_POOL_SEASONAL",
        category: "OUTDOOR",
        channels: {},
        label: "Seasonal Pool",
    },
    {
        amenity: "HAS_COMMUNAL_POOL",
        category: "OUTDOOR",
        channels: {},
        label: "Communal Pool",
    },
    {
        amenity: "HAS_HEATED_POOL",
        category: "OUTDOOR",
        channels: {},
        label: "Heated Pool",
    },
    {
        amenity: "HAS_INDOOR_POOL",
        category: "INDOOR",
        channels: {},
        label: "Indoor Pool",
    },
    {
        amenity: "HAS_INDOOR_POOL_ALL_YEAR",
        category: "INDOOR",
        channels: {},
        label: "Year-round Indoor Pool",
    },
    {
        amenity: "HAS_INDOOR_POOL_SEASONAL",
        category: "INDOOR",
        channels: {},
        label: "Seasonal Indoor Pool",
    },
    {
        amenity: "HAS_FENCED_POOL",
        category: "INDOOR",
        channels: {},
        label: "Fenced Pool",
    },
    {
        amenity: "HAS_FENCED_YARD",
        category: "INDOOR",
        channels: {},
        label: "Fenced Yard",
    },
    {
        amenity: "HAS_HOT_TUB",
        category: "OUTDOOR",
        channels: {},
        label: "Hot Tub",
    },
    {
        amenity: "HAS_FREE_PARKING",
        category: "OUTDOOR",
        channels: {},
        label: "Free Parking",
    },
    {
        amenity: "HAS_FREE_STREET_PARKING",
        category: "OUTDOOR",
        channels: {},
        label: "Free Street Parking",
    },
    {
        amenity: "HAS_PAID_OFF_PREMISES_PARKING",
        category: "OUTDOOR",
        channels: {},
        label: "Paid Off-premises Parking",
    },
    {
        amenity: "HAS_PAID_ON_PREMISES_PARKING",
        category: "OUTDOOR",
        channels: {},
        label: "Paid On-premises Parking",
    },
    {
        amenity: "HAS_EV_CAR_CHARGER",
        category: "OUTDOOR",
        channels: {},
        label: "EV Car Charger",
    },
    {
        amenity: "HAS_INDOOR_FIREPLACE",
        category: "INDOOR",
        channels: {},
        label: "Indoor Fireplace",
    },
    {
        amenity: "IS_WHEELCHAIR_ACCESSIBLE",
        category: "EXTRAS",
        channels: {},
        label: "Wheelchair Accessible",
    },
    {
        amenity: "HAS_SINGLE_LEVEL",
        category: "INDOOR",
        channels: {},
        label: "Single Level",
    },
    {
        amenity: "HAS_SMOKE_DETECTOR",
        category: "INDOOR",
        channels: {},
        label: "Smoke Detector",
    },
    {
        amenity: "HAS_FIRE_EXTINGUISHER",
        category: "INDOOR",
        channels: {},
        label: "Fire Extinguisher",
    },
    {
        amenity: "HAS_EMERGENCY_EXIT",
        category: "INDOOR",
        channels: {},
        label: "Emergency Exit",
    },
    {
        amenity: "HAS_DEADBOLT_LOCK",
        category: "INDOOR",
        channels: {},
        label: "Deadbolt Lock",
    },
    {
        amenity: "HAS_OUTDOOR_LIGHTING",
        category: "INDOOR",
        channels: {},
        label: "Outdoor Lighting",
    },
    {
        amenity: "HAS_ESSENTIALS",
        category: "INDOOR",
        channels: {},
        label: "Essentials",
    },
    {
        amenity: "HAS_BALCONY_TERRASSE",
        category: "OUTDOOR",
        channels: {},
        label: "Balcony/Terrace",
    },
    {
        amenity: "HAS_BABY_HIGH_CHAIR",
        category: "INDOOR",
        channels: {},
        label: "Baby High Chair",
    },
    {
        amenity: "HAS_BABY_TRAVEL_BED",
        category: "INDOOR",
        channels: {},
        label: "Baby Travel Bed",
    },
    {
        amenity: "HAS_CDDVD_PLAYER",
        category: "INDOOR",
        channels: {},
        label: "CD/DVD Player",
    },
    {
        amenity: "HAS_BOARD_GAMES",
        category: "INDOOR",
        channels: {},
        label: "Board Games",
    },
    {
        amenity: "HAS_BARBECUE",
        category: "OUTDOOR",
        channels: {},
        label: "Barbecue",
    },
    {
        amenity: "HAS_ELEVATOR",
        category: "EXTRAS",
        channels: {},
        label: "Elevator",
    },
    {
        amenity: "HAS_DEHUMIDIFIER",
        category: "INDOOR",
        channels: {},
        label: "Dehumidifier",
    },
    {
        amenity: "HAS_CEILING_FAN",
        category: "INDOOR",
        channels: {},
        label: "Ceiling Fan",
    },
    {
        amenity: "HAS_VENTILATION_FAN",
        category: "INDOOR",
        channels: {},
        label: "Ventilation Fan",
    },
    {
        amenity: "HAS_HAIR_DRYER",
        category: "INDOOR",
        channels: {},
        label: "Hair Dryer",
    },
    {
        amenity: "HAS_CROCKERY_CUTLERY",
        category: "INDOOR",
        channels: {},
        label: "Crockery and Cutlery",
    },
    {
        amenity: "HAS_POTS_PANS",
        category: "INDOOR",
        channels: {},
        label: "Pots and Pans",
    },
    {
        amenity: "HAS_OVEN",
        category: "INDOOR",
        channels: {},
        label: "Oven",
    },
    {
        amenity: "HAS_MICROWAVE_OVEN",
        category: "INDOOR",
        channels: {},
        label: "Microwave Oven",
    },
    {
        amenity: "HAS_WATER_KETTLE",
        category: "INDOOR",
        channels: {},
        label: "Water Kettle",
    },
    {
        amenity: "HAS_COFFEE_MAKER",
        category: "INDOOR",
        channels: {},
        label: "Coffee Maker",
    },
    {
        amenity: "HAS_DISHWASHER",
        category: "INDOOR",
        channels: {},
        label: "Dishwasher",
    },
    {
        amenity: "HAS_TOASTER",
        category: "INDOOR",
        channels: {},
        label: "Toaster",
    },
    {
        amenity: "HAS_FRIDGE",
        category: "INDOOR",
        channels: {},
        label: "Fridge",
    },
    {
        amenity: "HAS_KITCHEN_ISLAND",
        category: "INDOOR",
        channels: {},
        label: "Kitchen Island",
    },
    {
        amenity: "HAS_DINING_TABLE",
        category: "INDOOR",
        channels: {},
        label: "Dining Table",
    },
    {
        amenity: "HAS_ALARM_SYSTEM",
        category: "INDOOR",
        channels: {},
        label: "Alarm System",
    },
    {
        amenity: "HAS_BASKETBALL_COURT",
        category: "EXTRAS",
        channels: {},
        label: "Basketball Court",
    },
    {
        amenity: "HAS_CINEMA_ROOM",
        category: "EXTRAS",
        channels: {},
        label: "Cinema Room",
    },
    {
        amenity: "HAS_GATED_PROPERTY",
        category: "OUTDOOR",
        channels: {},
        label: "Gated Property",
    },
    {
        amenity: "HAS_HELIPAD",
        category: "OUTDOOR",
        channels: {},
        label: "Helipad",
    },
    {
        amenity: "HAS_GYM",
        category: "EXTRAS",
        channels: {},
        label: "Gym",
    },
    {
        amenity: "HAS_IPOD_STATION",
        category: "INDOOR",
        channels: {},
        label: "iPod Station",
    },
    {
        amenity: "HAS_JACUZZI",
        category: "INDOOR",
        channels: {},
        label: "Jacuzzi",
    },
    {
        amenity: "HAS_STEAM_ROOM",
        category: "INDOOR",
        channels: {},
        label: "Steam Room",
    },
    {
        amenity: "HAS_LIBRARY",
        category: "EXTRAS",
        channels: {},
        label: "Library",
    },
    {
        amenity: "HAS_MASSAGE_ROOM",
        category: "EXTRAS",
        channels: {},
        label: "Massage Room",
    },
    {
        amenity: "HAS_OFFICE",
        category: "EXTRAS",
        channels: {},
        label: "Office",
    },
    {
        amenity: "HAS_DESK",
        category: "INDOOR",
        channels: {},
        label: "Desk",
    },
    {
        amenity: "HAS_DESK_CHAIR",
        category: "INDOOR",
        channels: {},
        label: "Desk Chair",
    },
    {
        amenity: "HAS_COMPUTER_MONITOR",
        category: "INDOOR",
        channels: {},
        label: "Computer Monitor",
    },
    {
        amenity: "HAS_PRINTER",
        category: "INDOOR",
        channels: {},
        label: "Printer",
    },
    {
        amenity: "HAS_POOL_TABLE",
        category: "EXTRAS",
        channels: {},
        label: "Pool Table",
    },
    {
        amenity: "HAS_PIANO",
        category: "EXTRAS",
        channels: {},
        label: "Piano",
    },
    {
        amenity: "HAS_SAFE_BOX",
        category: "INDOOR",
        channels: {},
        label: "Safe Box",
    },
    {
        amenity: "HAS_CABINET_LOCKS",
        category: "INDOOR",
        channels: {},
        label: "Cabinet Locks",
    },
    {
        amenity: "HAS_SEA_VIEW",
        category: "OUTDOOR",
        channels: {},
        label: "Sea View",
    },
    {
        amenity: "HAS_SMART_HOME",
        category: "INDOOR",
        channels: {},
        label: "Smart Home",
    },
    {
        amenity: "HAS_SOCCER_FIELD",
        category: "EXTRAS",
        channels: {},
        label: "Soccer Field",
    },
    {
        amenity: "HAS_TENNIS",
        category: "EXTRAS",
        channels: {},
        label: "Tennis Court",
    },
    {
        amenity: "HAS_TOILETRIES",
        category: "EXTRAS",
        channels: {},
        label: "Toiletries",
    },
    {
        amenity: "HAS_WINE_CELLAR",
        category: "EXTRAS",
        channels: {},
        label: "Wine Cellar",
    },
    {
        amenity: "HAS_WARDROBE",
        category: "INDOOR",
        channels: {},
        label: "Wardrobe",
    },
    {
        amenity: "HAS_IRON",
        category: "INDOOR",
        channels: {},
        label: "Iron",
    },
    {
        amenity: "HAS_IRONING_FACILITIES",
        category: "INDOOR",
        channels: {},
        label: "Ironing Facilities",
    },
    {
        amenity: "HAS_SHAMPOO",
        category: "INDOOR",
        channels: {},
        label: "Shampoo",
    },
    {
        amenity: "HAS_BREAKFAST",
        category: "EXTRAS",
        channels: {},
        label: "Breakfast",
    },
    {
        amenity: "HAS_MEAL_DELIVERY",
        category: "EXTRAS",
        channels: {},
        label: "Meal Delivery",
    },
    {
        amenity: "HAS_BUZZER",
        category: "INDOOR",
        channels: {},
        label: "Buzzer",
    },
    {
        amenity: "HAS_DOORMAN",
        category: "EXTRAS",
        channels: {},
        label: "Doorman",
    },
    {
        amenity: "HAS_CARBON_MONOXIDE_DETECTOR",
        category: "EXTRAS",
        channels: {},
        label: "Carbon Monoxide Detector",
    },
    {
        amenity: "HAS_FIRST_AID_KIT",
        category: "INDOOR",
        channels: {},
        label: "First Aid Kit",
    },
    {
        amenity: "HAS_CAT",
        category: "INDOOR",
        channels: {},
        label: "Cat",
    },
    {
        amenity: "HAS_DOG",
        category: "INDOOR",
        channels: {},
        label: "Dog",
    },
    {
        amenity: "HAS_OTHER_PET",
        category: "INDOOR",
        channels: {},
        label: "Other Pet",
    },
    {
        amenity: "HAS_24_CHECKIN",
        category: "EXTRAS",
        channels: {},
        label: "24-hour Check-in",
    },
    {
        amenity: "HAS_SAFETY_CARD",
        category: "INDOOR",
        channels: {},
        label: "Safety Card",
    },
    {
        amenity: "HAS_HANGERS",
        category: "INDOOR",
        channels: {},
        label: "Hangers",
    },
    {
        amenity: "IS_LAPTOP_FRIENDLY",
        category: "INDOOR",
        channels: {},
        label: "Laptop Friendly",
    },
    {
        amenity: "HAS_LOCK_ON_BEDROOM",
        category: "EXTRAS",
        channels: {},
        label: "Lock on Bedroom",
    },
    {
        amenity: "HAS_PRIVATE_ENTRANCE",
        category: "OUTDOOR",
        channels: {},
        label: "Private Entrance",
    },
    {
        amenity: "HAS_BABY_BATH",
        category: "FAMILY",
        channels: {},
        label: "Baby Bath",
    },
    {
        amenity: "HAS_BABY_MONITOR",
        category: "FAMILY",
        channels: {},
        label: "Baby Monitor",
    },
    {
        amenity: "HAS_BABYSITTER_RECOMMENDATIONS",
        category: "FAMILY",
        channels: {},
        label: "Babysitter Recommendations",
    },
    {
        amenity: "HAS_BATHTUB",
        category: "FAMILY",
        channels: {},
        label: "Bathtub",
    },
    {
        amenity: "HAS_CHANGING_TABLE",
        category: "FAMILY",
        channels: {},
        label: "Changing Table",
    },
    {
        amenity: "HAS_CHILDRENS_BOOKS_AND_TOYS",
        category: "FAMILY",
        channels: {},
        label: "Children's Books and Toys",
    },
    {
        amenity: "HAS_OUTDOOR_PLAY_AREA",
        category: "EXTRAS",
        channels: {},
        label: "Outdoor Play Area",
    },
    {
        amenity: "HAS_CHILDRENS_DINNERWARE",
        category: "FAMILY",
        channels: {},
        label: "Children's Dinnerware",
    },
    {
        amenity: "HAS_CHILDCARE",
        category: "FAMILY",
        channels: {},
        label: "Childcare",
    },
    {
        amenity: "HAS_FIREPLACE_GUARDS",
        category: "FAMILY",
        channels: {},
        label: "Fireplace Guards",
    },
    {
        amenity: "HAS_GAME_CONSOLE",
        category: "FAMILY",
        channels: {},
        label: "Game Console",
    },
    {
        amenity: "HAS_OUTLET_COVERS",
        category: "FAMILY",
        channels: {},
        label: "Outlet Covers",
    },
    {
        amenity: "HAS_PACK_N_PLAY_TRAVEL_CRIB",
        category: "FAMILY",
        channels: {},
        label: "Pack 'n Play/Travel Crib",
    },
    {
        amenity: "HAS_ROOM_DARKENING_SHADES",
        category: "FAMILY",
        channels: {},
        label: "Room Darkening Shades",
    },
    {
        amenity: "HAS_STAIR_GATES",
        category: "FAMILY",
        channels: {},
        label: "Stair Gates",
    },
    {
        amenity: "HAS_TABLE_CORNER_GUARDS",
        category: "FAMILY",
        channels: {},
        label: "Table Corner Guards",
    },
    {
        amenity: "HAS_WINDOW_GUARDS",
        category: "FAMILY",
        channels: {},
        label: "Window Guards",
    },
    {
        amenity: "HAS_LAKE_ACCESS",
        category: "EXTRAS",
        channels: {},
        label: "Lake Access",
    },
    {
        amenity: "HAS_BEACH_FRONT",
        category: "EXTRAS",
        channels: {},
        label: "Beach Front",
    },
    {
        amenity: "HAS_WATER_FRONT",
        category: "EXTRAS",
        channels: {},
        label: "Water Front",
    },
    {
        amenity: "HAS_SKI_IN_SKI_OUT",
        category: "EXTRAS",
        channels: {},
        label: "Ski-in/Ski-out",
    },
    {
        amenity: "HAS_STOVE",
        category: "INDOOR",
        channels: {},
        label: "Stove",
    },
    {
        amenity: "CHECK_IN_OPTION",
        category: null,
        channels: {},
        label: "Check-in Option",
    },
    {
        amenity: "CHECK_IN_OPTION_INSTRUCTION",
        category: null,
        channels: {},
        label: "Check-in Option Instruction",
    },
    {
        amenity: "HAS_LINENS",
        category: "INDOOR",
        channels: {},
        label: "Linens",
    },
    {
        amenity: "HAS_TOWELS",
        category: "INDOOR",
        channels: {},
        label: "Towels",
    },
    {
        amenity: "HAS_HOT_WATER",
        category: "INDOOR",
        channels: {},
        label: "Hot Water",
    },
    {
        amenity: "HAS_COOKING_BASICS",
        category: "INDOOR",
        channels: {},
        label: "Cooking Basics",
    },
    {
        amenity: "HAS_SURVEILLANCE",
        category: "INDOOR",
        channels: {},
        label: "Surveillance",
    },
    {
        amenity: "HAS_GARDEN",
        category: "OUTDOOR",
        channels: {},
        label: "Garden",
    },
    {
        amenity: "HAS_DECK_PATIO",
        category: "OUTDOOR",
        channels: {},
        label: "Deck/Patio",
    },
    {
        amenity: "HAS_AIR_FILTER",
        category: "INDOOR",
        channels: {},
        label: "Air Filter",
    },
    {
        amenity: "HAS_ENHANCED_CLEANING",
        category: "INDOOR",
        channels: {},
        label: "Enhanced Cleaning",
    },
    {
        amenity: "HAS_CLEANING_WITH_DISINFECTANTS",
        category: "INDOOR",
        channels: {},
        label: "Cleaning with Disinfectants",
    },
    {
        amenity: "HAS_HIGH_TOUCH_SURFACES_CLEANING_WITH_DISINFECTANTS",
        category: "INDOOR",
        channels: {},
        label: "High-touch Surfaces Cleaning with Disinfectants",
    },
    {
        amenity: "HAS_IN_PERSON_CHECKIN",
        category: "EXTRAS",
        channels: {},
        label: "In-person Check-in",
    },
    {
        amenity: "HAS_CONTACTLESS_CHECKIN",
        category: "EXTRAS",
        channels: {},
        label: "Contactless Check-in",
    },
    {
        amenity: "HAS_CONCIERGE",
        category: "EXTRAS",
        channels: {},
        label: "Concierge",
    },
    {
        amenity: "HAS_OCEAN_FRONT",
        category: "EXTRAS",
        channels: {},
        label: "Ocean Front",
    },
    {
        amenity: "IS_RESORT",
        category: "EXTRAS",
        channels: {},
        label: "Resort",
    },
    {
        amenity: "IS_RURAL",
        category: "EXTRAS",
        channels: {},
        label: "Rural",
    },
    {
        amenity: "HAS_TOWN",
        category: "EXTRAS",
        channels: {},
        label: "Town",
    },
    {
        amenity: "HAS_WATER_VIEW",
        category: "EXTRAS",
        channels: {},
        label: "Water View",
    },
    {
        amenity: "IS_DOWNTOWN",
        category: "EXTRAS",
        channels: {},
        label: "Downtown",
    },
    {
        amenity: "HAS_GOLF_COURSE_VIEW",
        category: "EXTRAS",
        channels: {},
        label: "Golf Course View",
    },
    {
        amenity: "IS_LAKEFRONT",
        category: "EXTRAS",
        channels: {},
        label: "Lakefront",
    },
    {
        amenity: "HAS_MOUNTAIN",
        category: "EXTRAS",
        channels: {},
        label: "Mountain",
    },
    {
        amenity: "IS_NEAR_OCEAN",
        category: "EXTRAS",
        channels: {},
        label: "Near Ocean",
    },
    {
        amenity: "HAS_RIVER",
        category: "EXTRAS",
        channels: {},
        label: "River",
    },
    {
        amenity: "HAS_VILLAGE",
        category: "EXTRAS",
        channels: {},
        label: "Village",
    },
    {
        amenity: "HAS_BEACH",
        category: "EXTRAS",
        channels: {},
        label: "Beach",
    },
    {
        amenity: "HAS_BEACH_VIEW",
        category: "EXTRAS",
        channels: {},
        label: "Beach View",
    },
    {
        amenity: "IS_GOLF_COURSE_FRONT",
        category: "EXTRAS",
        channels: {},
        label: "Golf Course Front",
    },
    {
        amenity: "HAS_LAKE",
        category: "EXTRAS",
        channels: {},
        label: "Lake",
    },
    {
        amenity: "HAS_LAKE_VIEW",
        category: "EXTRAS",
        channels: {},
        label: "Lake View",
    },
    {
        amenity: "HAS_MOUNTAIN_VIEW",
        category: "EXTRAS",
        channels: {},
        label: "Mountain View",
    },
    {
        amenity: "HAS_BAKING_SHEET",
        category: "INDOOR",
        channels: {},
        label: "Baking Sheet",
    },
    {
        amenity: "HAS_BARBEQUE_UTENSILS",
        category: "OUTDOOR",
        channels: {},
        label: "Barbeque Utensils",
    },
    {
        amenity: "HAS_BEACH_ESSENTIALS",
        category: "OUTDOOR",
        channels: {},
        label: "Beach Essentials",
    },
    {
        amenity: "HAS_BIDET",
        category: "INDOOR",
        channels: {},
        label: "Bidet",
    },
    {
        amenity: "HAS_BIKES_FOR_RENT",
        category: "OUTDOOR",
        channels: {},
        label: "Bikes for Rent",
    },
    {
        amenity: "HAS_BLENDER",
        category: "INDOOR",
        channels: {},
        label: "Blender",
    },
    {
        amenity: "HAS_BOAT_SLIP",
        category: "OUTDOOR",
        channels: {},
        label: "Boat Slip",
    },
    {
        amenity: "HAS_BODY_SOAP",
        category: "INDOOR",
        channels: {},
        label: "Body Soap",
    },
    {
        amenity: "HAS_BREAD_MAKER",
        category: "INDOOR",
        channels: {},
        label: "Bread Maker",
    },
    {
        amenity: "HAS_CLEANING_PRODUCTS",
        category: "INDOOR",
        channels: {},
        label: "Cleaning Products",
    },
    {
        amenity: "HAS_CLOTHES_DRYING_RACK",
        category: "INDOOR",
        channels: {},
        label: "Clothes Drying Rack",
    },
    {
        amenity: "HAS_COFFEE",
        category: "INDOOR",
        channels: {},
        label: "Coffee",
    },
    {
        amenity: "HAS_CONDITIONER",
        category: "INDOOR",
        channels: {},
        label: "Conditioner",
    },
    {
        amenity: "HAS_ETHERNET_CONNECTION",
        category: "INDOOR",
        channels: {},
        label: "Ethernet Connection",
    },
    {
        amenity: "HAS_EXERCISE_EQUIPMENT",
        category: "INDOOR",
        channels: {},
        label: "Exercise Equipment",
    },
    {
        amenity: "HAS_EXTRA_PILLOWS_AND_BLANKETS",
        category: "INDOOR",
        channels: {},
        label: "Extra Pillows and Blankets",
    },
    {
        amenity: "HAS_FIRE_PIT",
        category: "OUTDOOR",
        channels: {},
        label: "Fire Pit",
    },
    {
        amenity: "HAS_FREEZER",
        category: "INDOOR",
        channels: {},
        label: "Freezer",
    },
    {
        amenity: "HAS_HAMMOCK",
        category: "OUTDOOR",
        channels: {},
        label: "Hammock",
    },
    {
        amenity: "HAS_LAUNDROMAT_NEARBY",
        category: "EXTRAS",
        channels: {},
        label: "Laundromat Nearby",
    },
    {
        amenity: "HAS_KAYAK",
        category: "OUTDOOR",
        channels: {},
        label: "Kayak",
    },
    {
        amenity: "HAS_MINI_FRIDGE",
        category: "INDOOR",
        channels: {},
        label: "Mini Fridge",
    },
    {
        amenity: "HAS_MOSQUITO_NET",
        category: "INDOOR",
        channels: {},
        label: "Mosquito Net",
    },
    {
        amenity: "HAS_OUTDOOR_KITCHEN",
        category: "OUTDOOR",
        channels: {},
        label: "Outdoor Kitchen",
    },
    {
        amenity: "HAS_OUTDOOR_SEATING",
        category: "OUTDOOR",
        channels: {},
        label: "Outdoor Seating",
    },
    {
        amenity: "HAS_PING_PONG_TABLE",
        category: "INDOOR",
        channels: {},
        label: "Ping Pong Table",
    },
    {
        amenity: "HAS_POCKET_WIFI",
        category: "INDOOR",
        channels: {},
        label: "Pocket WiFi",
    },
    {
        amenity: "HAS_PORTABLE_FANS",
        category: "INDOOR",
        channels: {},
        label: "Portable Fans",
    },
    {
        amenity: "HAS_RAIN_SHOWER",
        category: "INDOOR",
        channels: {},
        label: "Rain Shower",
    },
    {
        amenity: "HAS_RECORD_PLAYER",
        category: "INDOOR",
        channels: {},
        label: "Record Player",
    },
    {
        amenity: "HAS_RESORT_ACCESS",
        category: "EXTRAS",
        channels: {},
        label: "Resort Access",
    },
    {
        amenity: "HAS_RICE_MAKER",
        category: "INDOOR",
        channels: {},
        label: "Rice Maker",
    },
    {
        amenity: "HAS_SAFE",
        category: "INDOOR",
        channels: {},
        label: "Safe",
    },
    {
        amenity: "HAS_SHOWER_GEL",
        category: "INDOOR",
        channels: {},
        label: "Shower Gel",
    },
    {
        amenity: "HAS_SOUND_SYSTEM",
        category: "INDOOR",
        channels: {},
        label: "Sound System",
    },
    {
        amenity: "HAS_TRASH_COMPACTER",
        category: "INDOOR",
        channels: {},
        label: "Trash Compactor",
    },
    {
        amenity: "HAS_WINE_GLASSES",
        category: "INDOOR",
        channels: {},
        label: "Wine Glasses",
    },
    {
        amenity: "INVOICE_PROVIDED",
        category: "EXTRAS",
        channels: {},
        label: "Invoice Provided",
    },
];

export const propertyTypeGroups = [
    { value: "apartments", label: "Apartments" },
    { value: "bnb", label: "BNB" },
    { value: "boutique_hotels_and_more", label: "Boutique Hotels and More" },
    { value: "houses", label: "Houses" },
    { value: "secondary_units", label: "Secondary Units" },
    { value: "unique_homes", label: "Unique Homes" },
];

export const propertyTypeCategories = [
    { value: "aparthotel", label: "Aparthotel" },
    { value: "apartment", label: "Apartment" },
    { value: "barn", label: "Barn" },
    { value: "bnb", label: "BNB" },
    { value: "boat", label: "Boat" },
    { value: "boutique_hotel", label: "Boutique Hotel" },
    { value: "bungalow", label: "Bungalow" },
    { value: "cabin", label: "Cabin" },
    { value: "campsite", label: "Campsite" },
    { value: "casa_particular", label: "Casa Particular" },
    { value: "castle", label: "Castle" },
    { value: "cave", label: "Cave" },
    { value: "chalet", label: "Chalet" },
    { value: "condominium", label: "Condominium" },
    { value: "cottage", label: "Cottage" },
    { value: "cycladic_house", label: "Cycladic House" },
    { value: "dammuso", label: "Dammuso" },
    { value: "dome_house", label: "Dome House" },
    { value: "earthhouse", label: "Earthhouse" },
    { value: "farm_stay", label: "Farm Stay" },
    { value: "guest_suite", label: "Guest Suite" },
    { value: "guesthouse", label: "Guesthouse" },
    { value: "heritage_hotel", label: "Heritage Hotel" },
    { value: "holiday_park", label: "Holiday Park" },
    { value: "hostel", label: "Hostel" },
    { value: "hotel", label: "Hotel" },
    { value: "house", label: "House" },
    { value: "houseboat", label: "Houseboat" },
    { value: "hut", label: "Hut" },
    { value: "igloo", label: "Igloo" },
    { value: "island", label: "Island" },
    { value: "kezhan", label: "Kezhan" },
    { value: "lighthouse", label: "Lighthouse" },
    { value: "lodge", label: "Lodge" },
    { value: "loft", label: "Loft" },
    { value: "minsu", label: "Minsu" },
    { value: "pension", label: "Pension" },
    { value: "plane", label: "Plane" },
    { value: "ranch", label: "Ranch" },
    { value: "religious_building", label: "Religious Building" },
    { value: "resort", label: "Resort" },
    { value: "riad", label: "Riad" },
    { value: "rv", label: "RV" },
    { value: "ryokan", label: "Ryokan" },
    { value: "serviced_apartment", label: "Serviced Apartment" },
    { value: "shepherds_hut", label: "Shepherd's Hut" },
    { value: "shipping_container", label: "Shipping Container" },
    { value: "tent", label: "Tent" },
    { value: "tiny_house", label: "Tiny House" },
    { value: "tipi", label: "Tipi" },
    { value: "tower", label: "Tower" },
    { value: "townhouse", label: "Townhouse" },
    { value: "train", label: "Train" },
    { value: "treehouse", label: "Treehouse" },
    { value: "trullo", label: "Trullo" },
    { value: "villa", label: "Villa" },
    { value: "windmill", label: "Windmill" },
    { value: "yurt", label: "Yurt" },
];

export const listingViewOptions = [
    { label: 'Bay View', value: 'BAY_VIEW' },
    { label: 'Beach View', value: 'BEACH_VIEW' },
    { label: 'Canal View', value: 'CANAL_VIEW' },
    { label: 'City View', value: 'CITY_VIEW' },
    { label: 'Courtyard View', value: 'COURTYARD_VIEW' },
    { label: 'Desert View', value: 'DESERT_VIEW' },
    { label: 'Garden View', value: 'GARDEN_VIEW' },
    { label: 'Golf View', value: 'GOLF_VIEW' },
    { label: 'Harbor View', value: 'HARBOR_VIEW' },
    { label: 'Lake View', value: 'LAKE_VIEW' },
    { label: 'Marina View', value: 'MARINA_VIEW' },
    { label: 'Mountain View', value: 'MOUNTAIN_VIEW' },
    { label: 'Ocean View', value: 'OCEAN_VIEW' },
    { label: 'Park View', value: 'PARK_VIEW' },
    { label: 'Pool View', value: 'POOL_VIEW' },
    { label: 'Resort View', value: 'RESORT_VIEW' },
    { label: 'River View', value: 'RIVER_VIEW' },
    { label: 'Sea View', value: 'SEA_VIEW' },
    { label: 'Valley View', value: 'VALLEY_VIEW' },
    { label: 'Vineyard View', value: 'VINEYARD_VIEW' }
  ]

  export const checkInOptionCategories = [
    { label: 'Doorman Entry', value: 'doorman_entry' },
    { label: 'Lockbox', value: 'lockbox' },
    { label: 'Smartlock', value: 'smartlock' },
    { label: 'Keypad', value: 'keypad' },
    { label: 'Host Check-in', value: 'host_checkin' },
    { label: 'Other Check-in', value: 'other_checkin' }
  ]